{% set data = load_setup_py_data() %}

package:
  name: bactabolize
  version: {{ data.version }}

source:
  path: ../../

build:
  noarch: python
  number: 0

requirements:
  host:
    - python ==3.9
  run:
    - python ==3.9
    - biopython ==1.79
    - blast ==2.12.0
    - cobra ==0.21.0
    - prodigal ==2.6.3
    - filelock ==3.8.0
    # Additional requirements for MEMOTE (pip installed without dependencies in build.sh)
    - click-config-file
    - click-log
    - cookiecutter
    - depinfo ==1.7.0
    - gitpython
    - goodtables ~=2.0
    - importlib_resources
    - jinja2
    - numpydoc
    - pylru
    - pytest >=4.0
    - requests
    - sqlalchemy

test:
  commands:
    - bactabolize --version

about:
  home: {{ data.url }}
  license: {{ data.license }}
  summary: {{ data.description }}
