name: lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: requirements-dev.yaml
      - name: execute_precommit_hooks
        run: |
          pre-commit run \
            --verbose \
            --all-files
